ttools: escape > symbol in javadoc @return tag
This was causing a build error with Java 1.8:

    error: bad use of '>'

(cherry picked from commit 28ac47c090ce308d9dfedd0dc2283d0776d3858d)