parquet: upgrade hadoop from 3.2.3 to 3.4.3
Hadoop 3.2.3 doesn't work with Java 25+, because it uses terminally
deprecated SecurityManager-related parts of the Java API that
throw an UnsupportedOperationException from Java 23 or Java 24,
see JEP 486 (https://openjdk.org/jeps/486); specifically the
parquet unit tests and most anything else using the parquet I/O
handlers fail with:

   java.lang.UnsupportedOperationException: getSubject is not supported

This is fixed at Hadoop 3.4.3 and 3.5.0.  I believe that 3.5.* target
Java 17 so they're out, but 3.4.3 is still OK for Java 8.

The most recent Parquet-java version (1.18) has not upgraded Hadoop
in this way, so a parquet-java update won't help.  So this update
upgrades Hadoop independently.  Note this library combination is not
tested or endorsed by parquet-java, so problems might ensue.
But I'm trying it out to see what breaks.  It the update of jar files
in this commit seems to work for both java 8 and java 25
(previously parquet-related unit tests failed for java 25).
The weight of dependencies is increased, but only slightly,
from 21Mb to 23Mb.

The way that LZ4 compression fails has changed at this commit
in an uninteresting way, so adjust the corresponding unit test
accordingly.