ttools: escape < > symbols in javadoc @author tag
These were causing build errors with Java 1.8:

    error: malformed HTML

    error: bad use of '>'